import { useState } from 'react';
import { useSelector } from 'react-redux';
import { Sparkles, MapPin, Calendar, IndianRupee, Send } from 'lucide-react';
import LoadingSpinner from '../components/LoadingSpinner';
import api from '../services/api';

export default function AIItineraryPage() {
  const { isAuthenticated } = useSelector(s => s.auth);
  const [form, setForm] = useState({ destinationId: '', days: 3, budgetINR: 15000, hobbies: [] });
  const [destinations, setDest] = useState([]);
  const [itinerary, setItinerary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useState(() => {
    api.get('/destinations', { params: { limit: 50 } })
      .then(r => setDest(r.data?.destinations || []))
      .catch(() => {});
  }, []);

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!form.destinationId) { setError('Please select a destination'); return; }
    setLoading(true); setError(''); setItinerary(null);

    try {
      const res = await api.post('/ai/itinerary', form);
      setItinerary(res.data || res);
    } catch (err) { setError(err.message || 'Failed to generate itinerary'); }
    setLoading(false);
  };

  if (!isAuthenticated) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-20 text-center">
        <Sparkles size={48} className="mx-auto text-primary-400 mb-4" />
        <h1 className="section-title mb-4">AI Trip Planner</h1>
        <p className="text-surface-500 mb-6">Sign in to use the AI-powered trip planner</p>
        <a href="/login" className="btn-primary">Sign In</a>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 animate-fade-in">
      <div className="text-center mb-10">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary-50 text-primary-700 text-sm font-medium mb-4">
          <Sparkles size={16} /> Powered by AI
        </div>
        <h1 className="section-title mb-2">AI Trip Planner</h1>
        <p className="text-surface-500">Get a personalized day-by-day itinerary in seconds</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Form */}
        <div className="card p-6">
          <h2 className="font-display font-bold text-lg mb-4">Trip Details</h2>
          <form onSubmit={handleGenerate} className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-surface-700 mb-1.5">Destination</label>
              <select value={form.destinationId} onChange={e => setForm({...form, destinationId: e.target.value})} className="input-field" required>
                <option value="">Select destination</option>
                {destinations.map(d => <option key={d._id} value={d._id}>{d.name} — {d.location?.state}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-surface-700 mb-1.5">Duration (days)</label>
              <input type="number" min={1} max={14} value={form.days} onChange={e => setForm({...form, days: Number(e.target.value)})} className="input-field" />
            </div>
            <div>
              <label className="block text-sm font-medium text-surface-700 mb-1.5">Total Budget (₹)</label>
              <input type="number" min={1000} step={500} value={form.budgetINR} onChange={e => setForm({...form, budgetINR: Number(e.target.value)})} className="input-field" />
            </div>
            {error && <p className="text-red-500 text-sm">{error}</p>}
            <button type="submit" disabled={loading} className="btn-primary w-full flex items-center justify-center gap-2">
              {loading ? 'Generating...' : <><Send size={16} /> Generate Itinerary</>}
            </button>
          </form>
        </div>

        {/* Result */}
        <div className="lg:col-span-2">
          {loading ? <LoadingSpinner text="AI is crafting your perfect itinerary..." /> :
          itinerary?.itinerary ? (
            <div className="space-y-4">
              <div className="card-glass p-4 border border-primary-200 bg-primary-50/50">
                <p className="text-sm text-primary-700"><strong>{itinerary.destination?.name}</strong> · {itinerary.days} days · Budget ₹{itinerary.totalBudget?.toLocaleString()} · Generated by {itinerary.generatedBy}</p>
              </div>
              {itinerary.itinerary.map((day, i) => (
                <div key={i} className="card p-6 animate-slide-up" style={{ animationDelay: `${i * 100}ms` }}>
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary-500 to-accent-500 flex items-center justify-center text-white font-bold">{day.day}</div>
                    <h3 className="font-display font-bold text-lg">{day.title}</h3>
                  </div>
                  <ul className="space-y-2 mb-4">
                    {day.activities?.map((a, j) => (
                      <li key={j} className="flex items-start gap-2 text-sm text-surface-700">
                        <span className="text-primary-500 mt-0.5">•</span>{a}
                      </li>
                    ))}
                  </ul>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-4 pt-4 border-t border-surface-100">
                    {day.hotel && <div className="text-sm"><p className="font-medium text-surface-600">🏨 {day.hotel.name}</p><p className="text-surface-400">₹{day.hotel.pricePerNight}/night</p></div>}
                    {day.restaurant && <div className="text-sm"><p className="font-medium text-surface-600">🍽️ {day.restaurant.name}</p><p className="text-surface-400">{day.restaurant.cuisine}</p></div>}
                    {day.estimatedCost && <div className="text-sm"><p className="font-medium text-surface-600">💰 Day Cost</p><p className="text-surface-400">₹{day.estimatedCost.toLocaleString()}</p></div>}
                  </div>
                  {day.tips && <p className="text-xs text-surface-400 mt-3 italic">💡 {day.tips}</p>}
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-20">
              <Sparkles size={64} className="mx-auto text-surface-200 mb-4" />
              <p className="text-surface-500 text-lg">Fill in the details and let AI plan your trip!</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
